
library(devtools)
library(RMySQL)
library(dplyr)
#library(Hmisc)
library(xtable)
source("../sources/c.R")

library(ggplot2)
library(scales)
library(stringr)
library(data.table)
library(sp)
#library(sf)
library(mapview)
library(stringi)
library(igraph)
source("scripts/functions.R")
library(foreign)
library(cem)
library(geosphere)

