
library(devtools)
library(RMySQL)
library(dplyr)
#library(Hmisc)
library(xtable)
source("../sources/c.R")
source("scripts/functions.R")
library(ggplot2)
library(scales)
library(stringr)
library(data.table)
library(sp)
